export const airportName = [
    { code: "HAN", name: "Sân bay Quốc tế Nội Bài" },
    { code: "SGN", name: "Sân bay Quốc tế Tân Sơn Nhất" },
    { code: "DAD", name: "Sân bay Quốc tế Đà Nẵng" },
    { code: "VDO", name: "Sân bay Quốc tế Vân Đồn" },
    { code: "HPH", name: "Sân bay Quốc tế Cát Bi" },
    { code: "VII", name: "Sân bay Quốc tế Vinh" },
    { code: "HUI", name: "Sân bay Quốc tế Phú Bài" },
    { code: "CXR", name: "Sân bay Quốc tế Cam Ranh" },
    { code: "DLI", name: "Sân bay Quốc tế Liên Khương" },
    { code: "UIH", name: "Sân bay Quốc tế Phù Cát" },
    { code: "VCA", name: "Sân bay Quốc tế Cần Thơ" },
    { code: "PQC", name: "Sân bay Quốc tế Phú Quốc" },
    { code: "DIN", name: "Sân bay Điện Biên Phủ" },
    { code: "THD", name: "Sân bay Thọ Xuân" },
    { code: "VDH", name: "Sân bay Đồng Hới" },
    { code: "VCL", name: "Sân bay Chu Lai" },
    { code: "TBB", name: "Sân bay Tuy Hòa" },
    { code: "PXU", name: "Sân bay Pleiku" },
    { code: "BMV", name: "Sân bay Buôn Mê Thuột" },
    { code: "VKG", name: "Sân bay Rạch Giá" },
    { code: "CAH", name: "Sân bay Cà Mau" },
    { code: "VCS", name: "Sân bay Côn Đảo" }
];
